# Generated by Django 5.0.1 on 2024-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=60, verbose_name='Header Topic')),
                ('text', models.TextField(verbose_name='Header Text')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Header image')),
                ('button_text', models.CharField(max_length=40, verbose_name='Header Button text')),
            ],
        ),
    ]
