# Generated by Django 5.0.1 on 2024-01-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='main_topic',
        ),
    ]
