# Generated by Django 5.0.1 on 2024-01-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_service_main_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Service image')),
                ('topic', models.CharField(max_length=60, verbose_name='Service topic')),
                ('price', models.FloatField(verbose_name='Service price')),
            ],
        ),
    ]
