# Generated by Django 5.0.1 on 2024-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Customer name')),
                ('phone', models.CharField(max_length=20, verbose_name='Customer phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer email')),
                ('subject', models.CharField(max_length=80, verbose_name='Message Subject')),
                ('message', models.TextField(verbose_name='Customer message')),
            ],
        ),
    ]
