# Generated by Django 5.0.1 on 2024-01-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagee', models.ImageField(upload_to='images/', verbose_name='Worker image')),
                ('name', models.CharField(max_length=90, verbose_name='Worker name')),
                ('proffession', models.CharField(max_length=70, verbose_name='Worker proffession')),
            ],
        ),
    ]
