# Generated by Django 5.0.1 on 2024-01-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='imagee',
            new_name='image',
        ),
    ]
