# Generated by Django 5.0.1 on 2024-01-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_portfolio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
    ]
